### ISSUE TITLE
HTML File Play Button Not Executing Code in Acode

### ISSUE THREAD

**Issue by farhantanvir9z** [Acode-Foundation/Acode#1352]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

When editing an HTML file in Acode, clicking the Play button does not render or execute the HTML in the browser as expected. The button seems unresponsive or opens a blank page depending on the device.

### Environment

App version 1.11.3
Android version 11.
Web view version 137.0.7151.61

### If applicable, attach your Acode.log file to this issue.

<details><summary>Acode.log</summary><pre>

</pre></details>

**Comment by UnschooledGamer** [comment]
Which storage are you using, internal storage or other storage(i.e termux, sdcard)?

CC: @RohitKushvaha01 (assign?)

**Comment by RohitKushvaha01** [comment]
> Which storage are you using, internal storage or other storage(i.e termux, sdcard)?
> 
> CC: @RohitKushvaha01 (assign?)

Probably the same error reported on discord

**Comment by farhantanvir9z** [comment]
Internal storage.


Hi, I am Farhan.

Sorry. I understand the problem is occurred, because I did not save the
file.

But, In the previous version, the problem was not occured. Even when I
Didn't save the file.

Thank you very much.

Best regards,
Acode Foundation.

**Comment by farhantanvir9z** [comment]
# The problem is solved.
## By saving the file, the problem is solved.

**Comment by UnschooledGamer** [comment]
> Internal storage.
> 
> 
> Hi, I am Farhan.
> 
> Sorry. I understand the problem is occurred, because I did not save the
> file.
> 
> But, In the previous version, the problem was not occured. Even when I
> Didn't save the file.
> 
> Thank you very much.
> 
> Best regards,
> Acode Foundation.
> […](#)

Hmm, I had reported related to unsaved files in Acode's discord server. However, it's not resolved as they were busy with real-life tasks (e.g., exams, etc.).

Keep this issue open. We'll close it when it's resolved.

**Comment by vvep** [comment]
Still buggy in current latest 1.11.4-beta version

**Comment by bajrangCoder** [comment]
> Still buggy in current latest 1.11.4-beta version

Could you provide more information or steps to reproduce the issue?
Alternatively, feel free to open a new issue with additional details.

**Comment by Meedo-ema** [comment]
Same problem 
Blank page when I clicked on preview button

**Comment by RohitKushvaha01** [comment]
> Same problem 
> Blank page when I clicked on preview button 

Try the latest beta version
